In [1]:
import numpy as np
import pandas as pd

In [2]:
ventas_enero = np.random.randint(100,500,3)

In [3]:
ventas_enero

array([404, 371, 309], dtype=int32)

In [4]:
ventas_febrero = np.random.randint(100,500,3)

In [5]:
ventas_febrero

array([312, 234, 360], dtype=int32)

In [6]:
ventas_marzo = np.random.randint(100,500,3)

In [7]:
ventas_marzo

array([414, 163, 280], dtype=int32)

In [8]:
filas = ['ventas_enero', 'ventas_febrero', 'ventas_marzo']

In [9]:
filas

['ventas_enero', 'ventas_febrero', 'ventas_marzo']

In [10]:
columnas = ['oficina_1', 'oficina_2', 'oficina_3']

In [11]:
columnas

['oficina_1', 'oficina_2', 'oficina_3']

In [12]:
ventas = [ventas_enero, ventas_febrero, ventas_marzo]

In [13]:
ventas

[array([404, 371, 309], dtype=int32),
 array([312, 234, 360], dtype=int32),
 array([414, 163, 280], dtype=int32)]

In [14]:
dataframe = pd.DataFrame(ventas,filas,columnas)

In [15]:
dataframe

oficina_1  oficina_2  oficina_3
ventas_enero          404        371        309
ventas_febrero        312        234        360
ventas_marzo          414        163        280

In [18]:
ventas_enero_oficina_1 = dataframe['oficina_1']['ventas_enero']

In [19]:
ventas_enero_oficina_1

np.int32(404)

In [20]:
print("Las ventas de la oficina_1 son de {}".format(ventas_enero_oficina_1))

Las ventas de la oficina_1 son de 404
