# Random Forest - Clasificacion

In [1]:
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ls

 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 462B-5518

 Directorio de C:\Users\Vaquita

25/11/2025  16:31    <DIR>          .
25/11/2025  16:31    <DIR>          ..
05/09/2024  16:42    <DIR>          .anaconda
04/08/2025  03:22    <DIR>          .android
18/11/2025  20:29    <DIR>          .antigravity
25/11/2025  16:32    <DIR>          .conda
10/11/2025  09:40               103 .condarc
31/03/2025  17:44    <DIR>          .config
05/09/2024  15:15    <DIR>          .continuum
13/11/2025  14:25    <DIR>          .cufflinks
25/04/2025  02:55    <DIR>          .cursor
18/11/2025  20:29    <DIR>          .gemini
04/08/2025  03:14    <DIR>          .gradle
25/11/2025  16:31    <DIR>          .ipynb_checkpoints
05/09/2024  15:34    <DIR>          .ipython
13/01/2025  14:31    <DIR>          .jupyter
31/03/2025  17:45    <DIR>          .m2
05/11/2025  18:04    <DIR>          .matplotlib
01/04/2025  00:51    <DIR>          .openjfx
04/08/2025  03:17    

In [3]:
vinos = pd.read_csv('vino.csv')

In [4]:
vinos.head()

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Wine Type
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,One
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,One
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,One
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,One
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,One


In [5]:
X = vinos.drop('Wine Type', axis=1)
y = vinos['Wine Type']

In [6]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [9]:
from sklearn.ensemble import RandomForestClassifier

In [10]:
randomforest = RandomForestClassifier(n_estimators=80)

In [12]:
randomforest.fit(X_train, y_train)

,n_estimators,80
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [14]:
predicciones = randomforest.predict(X_test)

In [15]:
predicciones

array(['One', 'Three', 'One', 'One', 'One', 'Three', 'One', 'Three',
       'Two', 'Three', 'Three', 'One', 'Three', 'Two', 'Three', 'One',
       'Two', 'One', 'One', 'Two', 'One', 'One', 'Two', 'Two', 'Two',
       'Two', 'Three', 'Three', 'Three', 'Two', 'Two', 'Two', 'Three',
       'Three', 'Three', 'One', 'Two', 'Two', 'Two', 'Three', 'Two',
       'Two', 'One', 'Three', 'One', 'Two', 'One', 'One', 'Two', 'Three',
       'Three', 'One', 'Two', 'Three'], dtype=object)

In [16]:
y_test

58       One
138    Three
31       One
8        One
2        One
177    Three
24       One
135    Three
129      Two
147    Three
131    Three
53       One
169    Three
93       Two
173    Three
28       One
65       Two
45       One
0        One
77       Two
1        One
26       One
112      Two
91       Two
70       Two
103      Two
61       Two
159    Three
153    Three
85       Two
106      Two
92       Two
154    Three
132    Three
140    Three
29       One
117      Two
123      Two
115      Two
168    Three
71       Two
101      Two
37       One
164    Three
21       One
89       Two
54       One
3        One
74       Two
137    Three
174    Three
46       One
125      Two
139    Three
Name: Wine Type, dtype: object

In [17]:
from sklearn.metrics import classification_report, confusion_matrix

In [18]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       1.00      1.00      1.00        17
       Three       0.94      1.00      0.97        17
         Two       1.00      0.95      0.97        20

    accuracy                           0.98        54
   macro avg       0.98      0.98      0.98        54
weighted avg       0.98      0.98      0.98        54



In [19]:
print(confusion_matrix(y_test, predicciones))

[[17  0  0]
 [ 0 17  0]
 [ 0  1 19]]
