In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [5]:
ls

 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 462B-5518

 Directorio de C:\Users\Vaquita

21/11/2025  13:15    <DIR>          .
21/11/2025  13:15    <DIR>          ..
05/09/2024  16:42    <DIR>          .anaconda
04/08/2025  03:22    <DIR>          .android
18/11/2025  20:29    <DIR>          .antigravity
21/11/2025  13:15    <DIR>          .conda
10/11/2025  09:40               103 .condarc
31/03/2025  17:44    <DIR>          .config
05/09/2024  15:15    <DIR>          .continuum
13/11/2025  14:25    <DIR>          .cufflinks
25/04/2025  02:55    <DIR>          .cursor
18/11/2025  20:29    <DIR>          .gemini
04/08/2025  03:14    <DIR>          .gradle
21/11/2025  13:08    <DIR>          .ipynb_checkpoints
05/09/2024  15:34    <DIR>          .ipython
13/01/2025  14:31    <DIR>          .jupyter
31/03/2025  17:45    <DIR>          .m2
05/11/2025  18:04    <DIR>          .matplotlib
01/04/2025  00:51    <DIR>          .openjfx
04/08/2025  03:17    

In [8]:
vinos = pd.read_csv('vino.csv')
vinos.head()

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Wine Type
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,One
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,One
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,One
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,One
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,One


In [9]:
vinos['Wine Type'].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [11]:
vinos['Wine Type'].value_counts()

Wine Type
Two      71
One      59
Three    48
Name: count, dtype: int64

In [12]:
X = vinos.drop('Wine Type', axis=1)

In [13]:
y = vinos['Wine Type']

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
arbol = DecisionTreeClassifier()

In [21]:
arbol.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [22]:
predicciones = arbol.predict(X_test)

In [23]:
predicciones

array(['One', 'Two', 'Three', 'Two', 'One', 'One', 'Three', 'Three',
       'Two', 'Three', 'Two', 'Three', 'Two', 'Three', 'Three', 'Two',
       'One', 'Three', 'Two', 'One', 'Two', 'One', 'Two', 'One', 'Three',
       'Three', 'Two', 'One', 'Two', 'Three', 'Two', 'Two', 'Two', 'One',
       'Two', 'Two', 'Two', 'Two', 'Three', 'Two', 'One', 'Two', 'Three',
       'One', 'One', 'One', 'Three', 'Two', 'Three', 'Three', 'Three',
       'Two', 'Two', 'Three'], dtype=object)

In [24]:
from sklearn.metrics import classification_report, confusion_matrix

In [25]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       1.00      0.81      0.90        16
       Three       1.00      0.95      0.97        19
         Two       0.83      1.00      0.90        19

    accuracy                           0.93        54
   macro avg       0.94      0.92      0.92        54
weighted avg       0.94      0.93      0.93        54



In [26]:
print(confusion_matrix(y_test, predicciones))

[[13  0  3]
 [ 0 18  1]
 [ 0  0 19]]
