Métricas en árboles de decisión
El objetivo de este ejercicio es que los estudiantes implementen una función que:

Entrene un árbol de decisión usando DecisionTreeClassifier de sklearn.

Haga predicciones en un conjunto de prueba.

Evalúe el modelo utilizando métricas como precisión (accuracy), matriz de confusión y reporte de clasificación.

Pase pruebas unitarias (unittest) que validen el funcionamiento correcto del código.



Instrucciones

Implementa una función llamada entrenar_y_evaluar_arbol(X_train, y_train, X_test, y_test) que:

Entrene un modelo DecisionTreeClassifier con los datos de entrenamiento (X_train, y_train).

Prediga los valores de X_test.

Evalúe el modelo usando:

Precisión (accuracy_score)

Matriz de confusión (confusion_matrix)

Reporte de clasificación (classification_report)

Devuelva un diccionario con:

predicciones: Un array con las predicciones del modelo.

accuracy: Un número flotante con la precisión.

matriz_confusion: Una matriz de confusión.

reporte: Un string con el reporte de clasificación.

Usa random_state=42 en DecisionTreeClassifier para reproducibilidad.

Prueba la función con el dataset Iris, asegurando que el modelo tenga al menos 85% de precisión en los datos de prueba.



Ejemplo de Uso

Una vez implementada la función, debe ejecutarse correctamente con este código de prueba:



from sklearn.datasets import load_iris

from sklearn.model_selection import train_test_split

import numpy as np
 
# Cargar el dataset de flores Iris

iris = load_iris()

X = iris.data  # Características

y = iris.target  # Clases de las flores (Setosa, Versicolor, Virginica)
 
# Dividir en conjunto de entrenamiento (80%) y prueba (20%)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
 
# Importar la función implementada

from solution import entrenar_y_evaluar_arbol
 
# Llamar a la función y obtener las métricas

resultados = entrenar_y_evaluar_arbol(X_train, y_train, X_test, y_test)
 
# Mostrar los resultados

print("Precisión del modelo:", resultados["accuracy"])

print("Matriz de Confusión:\n", resultados["matriz_confusion"])

print("Reporte de Clasificación:\n", resultados["reporte"])


Salida esperada (aproximada):

Precisión del modelo: 1.0

Matriz de Confusión:

 [[10  0  0]
 
 [ 0  9  0]
 
 [ 0  0 11]]
 
Reporte de Clasificación:

               precision    recall  f1-score   support
 
      Setosa       1.00      1.00      1.00        10
      
  Versicolor       1.00      1.00      1.00         9
  
   Virginica       1.00      1.00      1.00        11
 
    accuracy                           1.00        30
    
   macro avg       1.00      1.00      1.00        30
   
weighted avg       1.00      1.00      1.00        30







Practicar con las métricas en los árboles de decisión


# Solucion:

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def entrenar_y_evaluar_arbol(X_train, y_train, X_test, y_test):

    clf = DecisionTreeClassifier(random_state=42)
    clf.fit(X_train, y_train)
    
    y_pred = clf.predict(X_test)
    
    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    nombres_clases = ['Setosa', 'Versicolor', 'Virginica']
    report = classification_report(y_test, y_pred, target_names=nombres_clases)
    
    resultados = {
        "predicciones": y_pred,
        "accuracy": acc,
        "matriz_confusion": cm,
        "reporte": report
    }
    
    return resultados

import unittest
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

class TestDecisionTreeMetrics(unittest.TestCase):
    
    def setUp(self):
        iris = load_iris()
        self.X = iris.data
        self.y = iris.target
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(
            self.X, self.y, test_size=0.2, random_state=42
        )

    def test_structure_and_accuracy(self):
        resultados = entrenar_y_evaluar_arbol(
            self.X_train, self.y_train, self.X_test, self.y_test
        )
        
        expected_keys = ["predicciones", "accuracy", "matriz_confusion", "reporte"]
        for key in expected_keys:
            self.assertIn(key, resultados, f"Falta la clave '{key}' en el resultado")
            
        self.assertIsInstance(resultados["matriz_confusion"], np.ndarray)
        self.assertIsInstance(resultados["accuracy"], float)
        self.assertGreaterEqual(resultados["accuracy"], 0.85, "La precisión es demasiado baja (< 85%)")
        
        print("\n✅ ¡Test completado con éxito! El modelo cumple los requisitos.")

if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

.
----------------------------------------------------------------------
Ran 1 test in 0.011s

OK



✅ ¡Test completado con éxito! El modelo cumple los requisitos.


Resultado:

Casos de prueba

Suspenso: 0, Aprobado: 4 de 4 pruebas

test_formato_matriz_confusion

test_precision_minima

test_reporte_clasificacion

test_salida_diccionario